---
- name : List summary of existing buckets in OCI object storage
  collections:
    - oracle.oci
  connection: local
  hosts: localhost
  tasks:
  - name: Initialize an empty list for compartment ids
    ansible.builtin.set_fact:
      compartment_id: ["ocid1.tenancy.oc1..aaaaaaaaso2ehakqgn5jmg7anrfbwztw6ost7vjpewtlwiye5gvztj4ijpdq"]
    delegate_to: localhost

  - name: Initialize an empty list for bucket list
    ansible.builtin.set_fact:
      bucket_list: []
    delegate_to: localhost

  - name: Initialize an empty list for bucket list
    ansible.builtin.set_fact:
      b1: []
    delegate_to: localhost


  - name: List compartments
    oci_identity_compartment_facts:
      # required
      parent_compartment_id: "ocid1.tenancy.oc1..aaaaaaaaso2ehakqgn5jmg7anrfbwztw6ost7vjpewtlwiye5gvztj4ijpdq"
      access_level: ANY
      compartment_id_in_subtree: true
    register: compartmentlist


  - name: Find matching instances
    ansible.builtin.set_fact:
      compartment_id: "{{ compartment_id + [item.id] }}"
    with_items: "{{ compartmentlist.compartments }}"

  - debug:
           var: compartment_id
  - name: List namespaces
    oci_log_analytics_namespace_facts:
      # required
      compartment_id: "ocid1.tenancy.oc1..aaaaaaaaso2ehakqgn5jmg7anrfbwztw6ost7vjpewtlwiye5gvztj4ijpdq"
    register: namespace_name

  - name: complete tasks
    include_tasks: bucketfromcompartment.yml


    loop: "{{compartment_id}}"
